export const getCountryCode = (nacionalidad: string): string => {
  const nacionalidades: { [key: string]: string } = {
    Argentino: 'ar',
    Brasilero: 'br',
    Chileno: 'cl',
    Colombiano: 'co',
    Méxicano: 'mx',
    Español: 'es',
    'Estados Unidos': 'us',
    Uruguayo: 'uy',
    Paraguayo: 'py',
    Boliviano: 'bo',
    Peruano: 'pe',
    Ecuatoriano: 'ec',
    Venezolano: 've',
    Cubano: 'cu',
    Dominicano: 'do',
    Puertorriqueño: 'pr',
    Panameño: 'pa',
    Costarricense: 'cr',
    Nicaragüense: 'ni',
    Hondureño: 'hn',
    Salvadoreño: 'sv',
    Guatemalteco: 'gt',
    Beliceño: 'bz',
    Canadiense: 'ca',
    Portugués: 'pt',
    Francés: 'fr',
    Italiano: 'it',
    Alemán: 'de',
    Británico: 'gb',
    Ruso: 'ru',
    Chino: 'cn',
    Japonés: 'jp',
    Coreano: 'kr',
    Indio: 'in',
    Australiano: 'au',
    Neozelandés: 'nz',
    Sudafricano: 'za',
    Egipcio: 'eg',
    Marroquí: 'ma',
    Nigeriano: 'ng',
    Keniata: 'ke',
    Turco: 'tr',
    Griego: 'gr',
    Sueco: 'se',
    Noruego: 'no',
    Danés: 'dk',
    Finlandés: 'fi',
    Holandés: 'nl',
    Belga: 'be',
    Suizo: 'ch',
    Austríaco: 'at',
    Polaco: 'pl',
    Checo: 'cz',
    Eslovaco: 'sk',
    Húngaro: 'hu',
    Rumano: 'ro',
    Búlgaro: 'bg',
    Ucraniano: 'ua',
    // Se pueden agregar más nacionalidades según sea necesario
  };

  return nacionalidades[nacionalidad] || 'Nacionalidad no encontrada';
};
